language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
  - dev
  - /^deploy-.*$/
before_install:
- npm install -g grunt-cli bower
install:
- npm install
- bower install
before_script:
- echo -e "Host bitbucket.org\n\tStrictKeyCheckingno\n" >> ~/.ssh/config
- git config --global user.email "patrick@pburtchaell.com"
- git config --global user.name "Patrick Burtchaell"
script: grunt build
after_script:
- echo -e "All done for now\n"
notifications:
  email:
    recepients:
    - patrick@pburtchaell.com
deploy:
  provider: s3
  access_key_id: AKIAJ6ZPHMZZUCUYCF6A
  secret_access_key:
    secure: BLA/KG6MdHRudCf7PRtpxeWh9n5ryVVKGenHEhrWJUCSCvfMMNWyjptZpeOeaNYa4/hJwJ/zpJkla/swHoMAOtEbel4NkJ173kRK/w1LoPoRsQNnjH/LkZqVPXDLFMNkn1137spHEI6zVd2KEcnFSoy4YcTGaSKdhIxYKcQs8I4=
  bucket: staging.pburtchaell.com
  local-dir: dist/
  on:
    repo: pburtchaell/site
    branch: dev
